### ISSUE TITLE
Scripts do not work on modern linux systems as p is missing from mmcblk0p1

### ISSUE THREAD

**Issue by carlos22** [themactep/device-wyze-v3#1]
Most modern systems use the p1 instead of 1 for mmc readers, esp if they are system integrated. Maybe there is a way to detect that with fdisk?

**Comment by themactep** [comment]
Can you elaborate what script and what part ot it exactly does not work for you?

**Comment by jjhdtv** [comment]
I'm having issues with the scripts.  Initially nothing.  Change the fdisk line to look for "Sd Card Reader".  Now it finds the device but scripts ends there.   fdisk -x | grep -B1 'SD  Card Reader' | head -1 | awk '{print $2}' | sed 's/://'

Detected Devices: /dev/sdc

I was able to get OpenIPC installed using other methods  but do not have the skills to get the required drivers loaded for the Wyze  V3.   Hence I was hoping to get the Sdcard2.sh to work.    I have UART access to the camera and can login into OpenIPC.  thanks for the effort on this project, I look forward to getting my cameras working.

**Comment by themactep** [comment]
what operating system is it? what version of fdisk?

**Comment by jjhdtv** [comment]
Running  Ubuntu 22.04.2 LTS.    fdisk -V   shows 2.37.2.  thanks

**Comment by themactep** [comment]
Why did you need to change anything if it works fine on Ubuntu 22.04?

```
root@119105759c66:/src/device-wyze/sdcards# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

root@119105759c66:/src/device-wyze/sdcards# fdisk -V
fdisk from util-linux 2.37.2

root@119105759c66:/src/device-wyze/sdcards# ./sdcard1.sh 
Usage: ./sdcard1.sh -d <SD card device>
Detected devices: /dev/sdd

root@119105759c66:/src/device-wyze/sdcards# ./sdcard1.sh -d /dev/sdd
 1) T10
 2) T20
 3) T31A
 4) T31AL
 5) T31L
 6) T31LC
 7) T31N
 8) T31X
 9) T31ZL
10) T31ZX
#? 5

All existing information on the card will be lost! Proceed? [Y/N]: Y
Creating a 64MB FAT32 partition on the SD card.
Mounting the partition to /tmp/tmp.WSjS6Wbe9f.
Downloading the latest OpenIPC firmware image.
Downloading firmware from https://openipc.org/cameras/vendors/ingenic/socs/t31l/download_full_image?flash_size=8&flash_type=nor&fw_release=lite
Unmounting the SD partition.

Card #1 created successfully.
The card is unmounted. You can safely remove it from the slot.

To install the OpenIPC firmware, login into camera bootloader shell
and run the following commands:

setenv baseaddr 0x80600000
setenv flashsize 0x1000000
mw.b ${baseaddr} 0xff ${flashsize}
fatload mmc 0:1 ${baseaddr} openipc-t31l-lite-8mb.bin
sf probe 0
sf erase 0x0 ${flashsize}
sf write ${baseaddr} 0x0 ${flashsize}
reset
```

**Comment by jjhdtv** [comment]
Below is what I get when I run the unmodified script:
```
jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ sudo ./sdcard1.sh
Usage: ./sdcard1.sh -d <SD card device>
Detected devices: jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ 

Below is what I get when I run the script with modifying the script as described above.  ( fdisk -x | grep -B1 'SD Card Reader' | head -1 | awk '{print $2}' | sed 's/://')

jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ sudo ./sdcard2.sh
Usage: ./sdcard2.sh -d <SD card device>
Detected devices: /dev/sdb
jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ 
```

In both cases the script stops.

**Comment by themactep** [comment]
It fails on reading/parsing the list of devices. Can you please post the output of `sudo fdisk -x`? I think some difference in the the outputs throws it off.

**Comment by jjhdtv** [comment]
```
jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ sudo ./sdcard1.sh
Usage: ./sdcard1.sh -d <SD card device>
Detected devices: jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ 


jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ sudo ./sdcard2.sh
Usage: ./sdcard2.sh -d <SD card device>
Detected devices: /dev/sdb
jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ 

jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ sudo fdisk -x
[sudo] password for jjhdtv: 
Disk /dev/loop0: 63.28 MiB, 66355200 bytes, 129600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop1: 4 KiB, 4096 bytes, 8 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop2: 63.91 MiB, 67014656 bytes, 130888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop3: 74.11 MiB, 77713408 bytes, 151784 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop4: 240.61 MiB, 252301312 bytes, 492776 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop5: 346.33 MiB, 363151360 bytes, 709280 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop6: 349.7 MiB, 366682112 bytes, 716176 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop7: 496.98 MiB, 521121792 bytes, 1017816 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sda: 93.16 GiB, 100030242816 bytes, 195371568 sectors
Disk model: HTS721010G9SA00 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: BB6BCBDD-BE33-4272-AC61-4DB3B8004A44
First LBA: 34
Last LBA: 195371534
Alternative LBA: 195371567
Partition entries LBA: 2
Allocated partition entries: 128

Device       Start       End   Sectors Type-UUID                            UUID                                 Name Attrs
/dev/sda1     2048      4095      2048 21686148-6449-6E6F-744E-656564454649 91492C54-B0D5-40A5-B342-515E0483FDB5      
/dev/sda2     4096   1054719   1050624 C12A7328-F81F-11D2-BA4B-00A0C93EC93B 422CEE6E-73BD-4E0C-8A8F-2B37C8974BAB EFI System Partition
                                                                                                                      
/dev/sda3  1054720 195371007 194316288 0FC63DAF-8483-4772-8E79-3D69D8477DE4 9ABC2139-3C12-4E00-B8F8-DE2D278C6E89      


Disk /dev/sdb: 29.54 GiB, 31719424000 bytes, 61952000 sectors
Disk model: SD Card Reader  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start      End  Sectors Id Type     Start-C/H/S  End-C/H/S Attrs
/dev/sdb1        8192 61951999 61943808  c W95 FAT3       0/1/1 784/254/63 


Disk /dev/loop8: 91.69 MiB, 96141312 bytes, 187776 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop9: 45.93 MiB, 48160768 bytes, 94064 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop10: 12.32 MiB, 12922880 bytes, 25240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop12: 40.86 MiB, 42840064 bytes, 83672 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop13: 304 KiB, 311296 bytes, 608 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop14: 452 KiB, 462848 bytes, 904 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/loop15: 40.43 MiB, 42393600 bytes, 82800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
jjhdtv@jjhdtv-HP-G42-Notebook-PC:~/Documents/sdcards$ 
```

**Comment by themactep** [comment]
damn, I feel deprived, lol

```
$ sudo fdisk -x
Disk /dev/sda: 953.87 GiB, 1024209543168 bytes, 2000409264 sectors
Disk model: Fanxiang S100 1T
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xfc760c36

Device     Boot      Start        End    Sectors Id Type                 Start-C/H/S  End-C/H/S Attrs
/dev/sda1  *          2048 1998407679 1998405632 83 Linux                      4/4/1 1023/254/2    80
/dev/sda2       1998409726 2000408575    1998850  5 Extended              1023/254/2 1023/254/2 
/dev/sda5       1998409728 2000408575    1998848 82 Linux swap / Solaris  1023/254/2 1023/254/2 


Disk /dev/nvme0n1: 931.51 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: WDC WDS100T2B0C                         
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: D320E6E6-AFE6-4D07-9741-145FFBA08A83
First usable LBA: 34
Last usable LBA: 1953525134
Alternative LBA: 1953525167
Partition entries starting LBA: 2
Allocated partition entries: 128
Partition entries ending LBA: 33

Device              Start        End    Sectors Type-UUID                            UUID                                 Name Attrs
/dev/nvme0n1p1       2048 1884162047 1884160000 0FC63DAF-8483-4772-8E79-3D69D8477DE4 94779EAE-63A9-4D71-BACE-2A437CE8AD3E home 
/dev/nvme0n1p2 1884162048 1953523711   69361664 0657FD6D-A4AB-43C4-84E5-0933C84B4F4F DB80C491-6C10-413F-ADA2-A76AB4A976D4      


Disk /dev/sdb: 1.36 TiB, 1500301910016 bytes, 2930277168 sectors
Disk model:                 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xec1c0f92

Device     Boot Start        End    Sectors Id Type  Start-C/H/S  End-C/H/S Attrs
/dev/sdb1        2048 2930276351 2930274304 83 Linux       4/4/1 1023/254/2 


Disk /dev/sdc: 223.57 GiB, 240057409536 bytes, 468862128 sectors
Disk model:                 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x29380568

Device     Boot Start       End   Sectors Id Type  Start-C/H/S   End-C/H/S Attrs
/dev/sdc1  *     2048 449806335 449804288 83 Linux     0/32/33 1023/254/63    80
```

Okay, thank you for the log, i'll look into the issue and report back with a fix.

**Comment by jjhdtv** [comment]
Hello again. Tried the scripts in Raspian.  Same results.  Script ends after "Detected devices" /dev/sda

jjhdtv@raspberrypi:~/Documents $ sudo ./sdcard2.sh
Usage: ./sdcard2.sh -d <SD card device>
Detected devices: /dev/sda
jjhdtv@raspberrypi:~/Documents $


jjhdtv@raspberrypi:~/Documents $ sudo fdisk -x
Disk /dev/ram0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram2: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram3: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram4: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram5: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram6: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram7: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram8: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram9: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram10: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram11: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram12: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram13: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram14: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram15: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/mmcblk0: 57.94 GiB, 62209916928 bytes, 121503744 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xc1718453

Device         Boot   Start       End   Sectors Id Type            Start-C/H/S   End-C/H/S Attrs
/dev/mmcblk0p1         8192   1056767   1048576  c W95 FAT32 (LBA)      64/0/1   1023/3/32
/dev/mmcblk0p2      1056768 121503743 120446976 83 Linux             1023/3/32 1023/254/63


Disk /dev/sda: 29.54 GiB, 31719424000 bytes, 61952000 sectors
Disk model: SD Card Reader
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start      End  Sectors Id Type            Start-C/H/S  End-C/H/S Attrs
/dev/sda1        8192 61951999 61943808  c W95 FAT32 (LBA)       0/1/1 784/254/63
jjhdtv@raspberrypi:~/Documents $

**Comment by themactep** [comment]
Do you tell the script what device to use at all?
Proper syntax of running the script is

`./sdcard2.sh -d /dev/sda`

or whatever sd card device you are going to use with it.

**Comment by jjhdtv** [comment]
Scripts are working once the proper syntax was used.  thanks

**Comment by themactep** [comment]
good, then i close this issue.
